name: flutter_github_search
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  cached_network_image:
  connectivity_plus:
  cookie_jar:
  cupertino_icons:
  dio:
  dio_cookie_manager:
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_localizations:
    sdk: flutter
  flutter_spinkit:
  font_awesome_flutter:
  freezed:
  freezed_annotation:
  gap:
  go_router:
  hooks_riverpod: 2.0.0-dev.5
  intl:
  json_annotation:
  package_info_plus:
  path_provider:
  shared_preferences:
  state_notifier:
  url_launcher:

dev_dependencies:
  build_runner:
  flutter_launcher_icons:
  flutter_lints:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.6

flutter:
  uses-material-design: true
  assets:
    - assets/json/env/
